name: Crawler CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0/15 * * * *"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Install dependencies
        run: |
          go mod tidy
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3
      - name: Build
        run: go build -o crawler
      - name: Test
        run: go test ./...
      - name: Lint
        run: golangci-lint run
      - name: Run
        run: ./crawler
      - name: Commit
        continue-on-error: true
        run: |
          git config --global user.name "yc97463"
          git config --global user.email "hi@imych.one"
          git add .
          git commit -m "Update announces."
      - name: Push Changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: dist
          force_orphan: false
          keep_files: true
